name: DeuteRaterEnvironment
channels:
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - altgraph=0.17.3=py38haa95532_0
  - blas=1.0=mkl
  - bokeh=2.4.3=py38haa95532_0
  - bottleneck=1.3.2=py38h2a96729_1
  - brotli=1.0.9=ha925a31_2
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2024.8.30=py38haa95532_0
  - click=8.1.7=py38haa95532_0
  - cloudpickle=3.0.0=py38haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.2=py38h2bbff1b_0
  - dask=2023.4.1=py38haa95532_0
  - dask-core=2023.4.1=py38haa95532_0
  - distributed=2023.4.1=py38haa95532_0
  - distro=1.5.0=pyhd3eb1b0_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - fsspec=2024.6.1=py38haa95532_0
  - future=0.18.3=py38haa95532_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - importlib-metadata=7.0.1=py38haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jinja2=3.1.4=py38haa95532_0
  - joblib=1.4.2=py38haa95532_0
  - jpeg=9d=h2bbff1b_0
  - kiwisolver=1.3.2=py38hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libwebp=1.2.2=h2bbff1b_0
  - locket=1.0.0=py38haa95532_0
  - lz4-c=1.9.3=h2bbff1b_1
  - markupsafe=2.1.3=py38h2bbff1b_0
  - matplotlib=3.5.1=py38haa95532_0
  - matplotlib-base=3.5.1=py38hd77b12b_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - msgpack-python=1.0.3=py38h59b6b97_0
  - munkres=1.1.4=py_0
  - numexpr=2.8.1=py38hb80d3ca_0
  - numpy=1.21.5=py38ha4e8547_0
  - numpy-base=1.21.5=py38hc2deb75_0
  - olefile=0.46=pyhd3eb1b0_0
  - openjdk=11.0.13=h2bbff1b_0
  - openssl=1.1.1w=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py38h6214cd6_0
  - partd=1.4.1=py38haa95532_0
  - pefile=2022.5.30=py38haa95532_0
  - pillow=8.4.0=py38hd45dc43_0
  - pip=24.2=py38haa95532_0
  - plotly=5.1.0=pyhd3eb1b0_0
  - powershell_shortcut=0.0.1=3
  - psutil=5.9.0=py38h2bbff1b_0
  - pyinstaller=5.6.2=py38h2bbff1b_0
  - pyinstaller-hooks-contrib=2022.14=py38haa95532_0
  - pymzml=2.4.7=py_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38hd77b12b_6
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-lmdb=1.4.1=py38hd77b12b_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=305=py38h2bbff1b_0
  - pywin32-ctypes=0.2.0=py38_1000
  - pyyaml=6.0=py38h2bbff1b_1
  - qt=5.9.7=vc14h73c81de_0
  - regex=2021.8.3=py38h2bbff1b_0
  - scikit-learn=1.3.0=py38h4ed8f06_1
  - scipy=1.7.3=py38h0a974cb_0
  - setuptools=58.0.4=py38haa95532_0
  - sip=4.19.13=py38hd77b12b_0
  - six=1.15.0=py38haa95532_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.37.2=h2bbff1b_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py38haa95532_0
  - threadpoolctl=3.5.0=py38h9909e9c_0
  - tk=8.6.11=h2bbff1b_0
  - toolz=0.12.0=py38haa95532_0
  - tornado=6.1=py38h2bbff1b_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - typing_extensions=4.11.0=py38haa95532_0
  - urllib3=2.2.3=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zict=3.0.0=py38haa95532_0
  - zipp=3.20.2=py38haa95532_0
  - zlib=1.2.11=h8cc25b3_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
      - more-itertools==10.5.0
prefix: C:\Users\Brigham Young Univ\.conda\envs\DeuteRaterEnvironment
